/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'project-categories': ProjectCategory;
    products: Product;
    'product-categories': ProductCategory;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'project-categories': ProjectCategoriesSelect<false> | ProjectCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'home-page': HomePage;
    'products-page': ProductsPage;
    'projects-page': ProjectsPage;
    'services-page': ServicesPage;
    'about-page': AboutPage;
    'footer-settings': FooterSetting;
    'custom-css': CustomCss;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'products-page': ProductsPageSelect<false> | ProductsPageSelect<true>;
    'projects-page': ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'footer-settings': FooterSettingsSelect<false> | FooterSettingsSelect<true>;
    'custom-css': CustomCssSelect<false> | CustomCssSelect<true>;
  };
  locale: 'en' | 'zh';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage admin and editor accounts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins can manage users. Editors can only manage content.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * All uploaded images and files are stored here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO. Not required for PDFs.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Manage completed and ongoing projects for the portfolio section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Auto-generated from the English title if left blank.
   */
  slug?: string | null;
  /**
   * Brief description shown in cards and listings (1–2 sentences).
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Select from the Project Categories collection.
   */
  projectCategory?: (number | null) | ProjectCategory;
  architect?: string | null;
  developer?: string | null;
  materialSupplied?: string | null;
  buildingType?: string | null;
  location?: string | null;
  completionDate?: string | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  publishedAt?: string | null;
  /**
   * Configure search engine and social media metadata for this content.
   */
  meta?: {
    /**
     * Page title shown in search results. Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Summary shown in search results. Recommended: 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma-separated keywords (optional).
     */
    keywords?: string | null;
    /**
     * Image shown when shared on social media. Recommended: 1200×630px.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Project categories used to filter and group projects.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories".
 */
export interface ProjectCategory {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Auto-generated from the English title if left blank.
   */
  slug?: string | null;
  /**
   * Representative image for this category.
   */
  image?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage products displayed in the Products section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * URL-friendly identifier. Auto-generated from the English title if left blank.
   */
  slug?: string | null;
  /**
   * One-line description shown in cards.
   */
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Select from the Product Categories collection.
   */
  productCategory?: (number | null) | ProductCategory;
  /**
   * Optional sub-group shown as a section heading within the category page.
   */
  subcategory?: string | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Configure search engine and social media metadata for this content.
   */
  meta?: {
    /**
     * Page title shown in search results. Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Summary shown in search results. Recommended: 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma-separated keywords (optional).
     */
    keywords?: string | null;
    /**
     * Image shown when shared on social media. Recommended: 1200×630px.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Product categories used to group products in the catalogue.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Auto-generated from the English title if left blank.
   */
  slug?: string | null;
  /**
   * Representative image for this category.
   */
  image?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'project-categories';
        value: number | ProjectCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  projectCategory?: T;
  architect?: T;
  developer?: T;
  materialSupplied?: T;
  buildingType?: T;
  location?: T;
  completionDate?: T;
  featured?: T;
  order?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories_select".
 */
export interface ProjectCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  productCategory?: T;
  subcategory?: T;
  featured?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site identity, domain, default SEO configuration, and indexing settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  /**
   * Your live site URL including https:// (e.g. https://yourdomain.com). Used for canonical URLs and SEO.
   */
  domain?: string | null;
  /**
   * Recommended: SVG or PNG with transparent background, max height 60px.
   */
  logo?: (number | null) | Media;
  /**
   * White version of the logo for use on dark backgrounds.
   */
  logoLight?: (number | null) | Media;
  /**
   * Recommended: 32×32px PNG or ICO file.
   */
  favicon?: (number | null) | Media;
  /**
   * Used on pages that do not have their own meta title/description configured.
   */
  defaultMeta?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * When enabled, the header stays fixed at the top of the page while scrolling.
   */
  stickyHeader?: boolean | null;
  /**
   * When enabled, adds a noindex meta tag to all pages, preventing search engines from indexing the site.
   */
  noindex?: boolean | null;
  /**
   * Enter full URLs including https:// for each platform.
   */
  socialLinks?: {
    facebook?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    whatsapp?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the main site navigation links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Drag to reorder. Add sub-items for dropdown menus.
   */
  items?:
    | {
        label: string;
        /**
         * Use relative paths: /about, /projects, /contact
         */
        href: string;
        openInNewTab?: boolean | null;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit homepage sections. Hero → Content > Hero Section. Services → Content > Services Section. About → Content > About Section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroSectionTitle?: string | null;
  heroSectionBody?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroSectionCtaText?: string | null;
  heroSectionCtaHref?: string | null;
  /**
   * Recommended: 1920×1080px or wider. A dark overlay is applied automatically.
   */
  heroSectionbackgroundImage?: (number | null) | Media;
  /**
   * Controls the darkness of the overlay on the background image.
   */
  heroSectionoverlayOpacity?: number | null;
  /**
   * Small uppercase text above the section title.
   */
  projectsSectionLabel?: string | null;
  projectsSectionTitle?: string | null;
  projectsCtaText?: string | null;
  projectsCtaHref?: string | null;
  featuredProductsTitle?: string | null;
  featuredProductsMode?: ('featured_products' | 'category_links') | null;
  /**
   * Configure up to 4 product category cards to display. Only used when Option 2 is selected.
   */
  featuredCategoryLinks?:
    | {
        categorySlug: 'silicone-sealants' | 'spacer-tapes' | 'suction-grip' | 'backer-rod';
        label?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  servicesSectionTitle?: string | null;
  servicesSectionCtaText?: string | null;
  servicesSectionCtaHref?: string | null;
  /**
   * Key numbers displayed as highlighted service.
   */
  servicesSectionHighlights?:
    | {
        servicesSectionHighlightsTitle: string;
        servicesSectionHighlightsDescription?: string | null;
        /**
         * Image displayed alongside the highlight.
         */
        servicesSectionHighlightsImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  aboutSectionTitle?: string | null;
  aboutSectionBody?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  aboutSectionCtaText?: string | null;
  aboutSectionCtaHref?: string | null;
  /**
   * Recommended: 50–60 characters. Shown in browser tabs and search results.
   */
  seoTitle?: string | null;
  /**
   * Recommended: 120–160 characters. Shown under the page title in search results.
   */
  seoDescription?: string | null;
  /**
   * Comma-separated keywords (optional).
   */
  seoKeywords?: string | null;
  /**
   * Recommended: 1200×630px. Used when the page is shared on social media.
   */
  seoOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the Products listing page title, subtitle, and SEO metadata.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page".
 */
export interface ProductsPage {
  id: number;
  /**
   * Main heading shown at the top of the Products page.
   */
  pageTitle: string;
  /**
   * Short introductory paragraph below the page title.
   */
  pageSubtitle?: string | null;
  /**
   * Configure search engine and social media metadata for this content.
   */
  meta?: {
    /**
     * Page title shown in search results. Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Summary shown in search results. Recommended: 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma-separated keywords (optional).
     */
    keywords?: string | null;
    /**
     * Image shown when shared on social media. Recommended: 1200×630px.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the Projects listing page title, subtitle, and SEO metadata.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page".
 */
export interface ProjectsPage {
  id: number;
  /**
   * Main heading shown at the top of the Projects page.
   */
  pageTitle: string;
  /**
   * Short introductory paragraph below the page title.
   */
  pageSubtitle?: string | null;
  /**
   * Configure search engine and social media metadata for this content.
   */
  meta?: {
    /**
     * Page title shown in search results. Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Summary shown in search results. Recommended: 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma-separated keywords (optional).
     */
    keywords?: string | null;
    /**
     * Image shown when shared on social media. Recommended: 1200×630px.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit the Services page title, intro text, and individual service items (via Collections > Services).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  /**
   * Main heading shown at the top of the Services page.
   */
  pageTitle?: string | null;
  /**
   * Introductory content below the page title. Supports bold, lists, links, images, etc.
   */
  pageSubtitle?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Key numbers displayed as highlighted service.
   */
  values?:
    | {
        name: string;
        /**
         * Image displayed alongside the value.
         */
        logo?: (number | null) | Media;
        /**
         * Value description content. Supports bold, lists, links, images, etc.
         */
        description?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Configure search engine and social media metadata for this content.
   */
  meta?: {
    /**
     * Page title shown in search results. Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Summary shown in search results. Recommended: 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma-separated keywords (optional).
     */
    keywords?: string | null;
    /**
     * Image shown when shared on social media. Recommended: 1200×630px.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit the About Us page content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  pageTitle?: string | null;
  /**
   * Main company introduction. Supports bold, italic, lists, links, images, etc.
   */
  pageBody?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  visionTitle?: string | null;
  visionBody?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  missionTitle?: string | null;
  missionBody?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  partnersTitle?: string | null;
  partners?:
    | {
        name: string;
        logo?: (number | null) | Media;
        /**
         * Use if logo is hosted externally. Leave blank to use the uploaded logo.
         */
        logoUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Configure search engine and social media metadata for this content.
   */
  meta?: {
    /**
     * Page title shown in search results. Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Summary shown in search results. Recommended: 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma-separated keywords (optional).
     */
    keywords?: string | null;
    /**
     * Image shown when shared on social media. Recommended: 1200×630px.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage footer content: contact info visibility, copyright, and back-to-top button.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings".
 */
export interface FooterSetting {
  id: number;
  title?: string | null;
  address?: string | null;
  email?: string | null;
  phone?: string | null;
  fax?: string | null;
  /**
   * e.g. Mon–Fri: 9:00am – 6:00pm
   */
  businessHours?: string | null;
  /**
   * Go to Google Maps → Share → Embed a map → Copy only the src="..." URL from the iframe code.
   */
  mapEmbedUrl?: string | null;
  /**
   * Display the contact form on the Contact page.
   */
  contactFormEnabled?: boolean | null;
  /**
   * Display address, phone, email and fax from Layout > Contact Information in the footer top section.
   */
  showContactInfo?: boolean | null;
  /**
   * e.g. "© 2025 Company Name. All rights reserved."
   */
  copyrightText?: string | null;
  /**
   * Display a scroll-to-top arrow button in the footer bottom bar.
   */
  showBackToTop?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Inject custom CSS that will be applied globally across the entire frontend site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-css".
 */
export interface CustomCss {
  id: number;
  /**
   * Write valid CSS here. It will be injected into a <style> tag on every page. Use carefully — bad CSS can break the layout.
   */
  css?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  domain?: T;
  logo?: T;
  logoLight?: T;
  favicon?: T;
  defaultMeta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
      };
  stickyHeader?: T;
  noindex?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        linkedin?: T;
        twitter?: T;
        instagram?: T;
        youtube?: T;
        whatsapp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroSectionTitle?: T;
  heroSectionBody?: T;
  heroSectionCtaText?: T;
  heroSectionCtaHref?: T;
  heroSectionbackgroundImage?: T;
  heroSectionoverlayOpacity?: T;
  projectsSectionLabel?: T;
  projectsSectionTitle?: T;
  projectsCtaText?: T;
  projectsCtaHref?: T;
  featuredProductsTitle?: T;
  featuredProductsMode?: T;
  featuredCategoryLinks?:
    | T
    | {
        categorySlug?: T;
        label?: T;
        image?: T;
        id?: T;
      };
  servicesSectionTitle?: T;
  servicesSectionCtaText?: T;
  servicesSectionCtaHref?: T;
  servicesSectionHighlights?:
    | T
    | {
        servicesSectionHighlightsTitle?: T;
        servicesSectionHighlightsDescription?: T;
        servicesSectionHighlightsImage?: T;
        id?: T;
      };
  aboutSectionTitle?: T;
  aboutSectionBody?: T;
  aboutSectionCtaText?: T;
  aboutSectionCtaHref?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoKeywords?: T;
  seoOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page_select".
 */
export interface ProductsPageSelect<T extends boolean = true> {
  pageTitle?: T;
  pageSubtitle?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  pageTitle?: T;
  pageSubtitle?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  pageTitle?: T;
  pageSubtitle?: T;
  values?:
    | T
    | {
        name?: T;
        logo?: T;
        description?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  pageTitle?: T;
  pageBody?: T;
  visionTitle?: T;
  visionBody?: T;
  missionTitle?: T;
  missionBody?: T;
  partnersTitle?: T;
  partners?:
    | T
    | {
        name?: T;
        logo?: T;
        logoUrl?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  title?: T;
  address?: T;
  email?: T;
  phone?: T;
  fax?: T;
  businessHours?: T;
  mapEmbedUrl?: T;
  contactFormEnabled?: T;
  showContactInfo?: T;
  copyrightText?: T;
  showBackToTop?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-css_select".
 */
export interface CustomCssSelect<T extends boolean = true> {
  css?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}